language: python
python:
  - 3.4
  - 3.5
  - 3.6
#  - pypy3.5-5.8.0
install:
  - pip install python-coveralls
  - python setup.py install
script:
  - python setup.py test
after_success:
  - sed -i -e 's/^\(concurrency = \'multiprocessing\'\)$/#\1/g' setup.cfg
  - coveralls
  - sed -i -e 's/^#\(concurrency = \'multiprocessing\'\)$/\1/g' setup.cfg
