sudo: false
dist: xenial
language: python
python:
  - 3.4
  - 3.5
  - 3.6
  - 3.7
  - 3.8
  - pypy3.5
  - pypy3.6
install:
  - pip install -U pip setuptools
  - python setup.py install
script:
  - pip install 'py>=1.5.0' pytest-runner pytest pytest-cov 'coverage>=4.2'
  - python setup.py test
after_success:
  - pip install codecov
  - codecov
