dist: xenial
language: python
python:
  - 3.4
  - 3.5
  - 3.6
  - 3.7
  - 3.8
  - 3.9-dev
  #- pypy3.5
  #- pypy3.6-7.3.1
install:
  - pip install tox-travis
script:
  - tox
  - tox -e lint
after_success:
  - pip install codecov
  - codecov
